name: mansil
description: A multi-language ANSI codes library.
version: 0.1.2
repository: https://github.com/vieolo/mansil

environment:
  sdk: ^3.10.7

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
